# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f6c592f79e7f472318451fec1909f0b664ee88ca4c400cbde077454a7b2cac5677d209e03f989b9bd0945bc8ce3e01058badb44f113f14dfaf39743efc3552b9

test:
  secret_key_base: c80e66f16c98cd3753fce76a9003ffdf7406d156b3d429c9516c6aa007d924cb7210cbbba76111c4cd8a6af7d4e8f084ae9784e24521ad2e4e520f4c79d9c28f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
